version: "2"

services:
  file-store:
    image: tianon/true
    volumes:
      - /data/public:/home/data

  database-store:
    image: tianon/true
    volumes:
      - /data/db:/data/db

  mongo:
    image: mongo:latest
    command: mongod
    links:
      - database-store

  dev:
    build: .
    ports:
      - "9095:8080"
    command: bash -c "yarn && yarn run dev"
    links:
      - mongo
      - file-store
    volumes:
      - .:/home/apps/app

  prod:
    build: .
    ports:
      - "9095:8080"
    command: bash -c "yarn && yarn run start"
    links:
      - mongo
      - file-store
    volumes:
      - .:/home/apps/app
